version: '3.8'

services:

  api:
    build: ./backend
    image: social-downloader
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/.venv
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_DB_KEY=${TELEGRAM_DB_KEY}
      - TELEGRAM_DIR=${TELEGRAM_DIR}