version: '3.8'

services:

  db:
    image: mongo
    container_name: social-downloader-db
    ports:
      - 27017:27017
    volumes: 
      - mongo_data:/data/db
      - ./db_init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=social-downloader
    networks:
      - social-downloader-net

  redis:
    image: redis:alpine3.18
    container_name: social-downloader-redis
    volumes:
      - redis_data:/data
    networks:
      - social-downloader-net
      
  api:
    build: ./backend
    image: social-downloader-api
    container_name: social-downloader-api
    ports:
      - 4000:8000
    command: >
      sh -c "celery -A celery_tasks.telegram_tasks worker --concurrency=1 --detach --loglevel=INFO --logfile telegram_worker.log &&
             uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - ./backend:/usr/src/app/
      - venv:/usr/src/app/.venv
      - telegram_cache:${TELEGRAM_DIR}
    environment:
      - SECRET=${SECRET}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_DB_KEY=${TELEGRAM_DB_KEY}
      - TELEGRAM_DIR=${TELEGRAM_DIR}
    networks:
      - social-downloader-net
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower
    container_name: social-downloader-monitoring
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - social-downloader-net
    depends_on:
      - redis
      - api
    
  frontend:
    build: ./frontend
    image: social-downloader-frontend
    container_name: social-downloader-frontend
    ports:
      - 80:5173
    command: npm run dev -- --host
    volumes:
      - ./frontend:/usr/src/frontend/
      - node_modules:/usr/src/frontend/node_modules
    environment:
      - SECRET=${SECRET}
    networks:
      - social-downloader-net
    depends_on:
      - api
      - redis
      - db

volumes:
  mongo_data:
  redis_data:
  venv:
  node_modules:
  telegram_cache:

networks:
  social-downloader-net:
