version: '3.8'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      
  api:
    build: ./backend
    image: social-downloader
    ports:
      - 4000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/usr/src/app/
      - venv:/usr/src/app/.venv
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_DB_KEY=${TELEGRAM_DB_KEY}
      - TELEGRAM_DIR=${TELEGRAM_DIR}

  ui:
    build: ./frontend
    image: social-downloader-ui
    ports:
      - 8000:5173
    command: npm run dev -- --host
    volumes:
      - ./frontend:/usr/src/frontend/
      - node_modules:/usr/src/frontend/node_modules

volumes:
  venv:
  node_modules:
