version: '3.8'

services:

  db:
    image: mongo
    container_name: social-downloader-db
    ports:
      - 27017:27017
    restart: always
    volumes: 
      - mongo_data:/data/db
      - ./db_init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=social-downloader
    networks:
      - social-downloader-net

  rabbitmq:
    image: rabbitmq:alpine
    container_name: social-downloader-rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - social-downloader-net
      
  api:
    build: ./backend
    image: social-downloader-api
    container_name: social-downloader-api
    ports:
      - 4000:8000
    command: >
      sh -c "celery -A celery_tasks.telegram_tasks worker --detach --loglevel=INFO --time-limit=86400 &&
             uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - ./backend:/usr/src/app/
      - venv:/usr/src/app/.venv
      - telegram_cache:${TELEGRAM_DIR}
    environment:
      - SECRET=${SECRET}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_DB_KEY=${TELEGRAM_DB_KEY}
      - TELEGRAM_DIR=${TELEGRAM_DIR}
    networks:
      - social-downloader-net
    depends_on:
      - rabbitmq
      - db

  frontend:
    build: ./frontend
    image: social-downloader-frontend
    container_name: social-downloader-frontend
    ports:
      - 8000:5173
    command: npm run dev -- --host
    volumes:
      - ./frontend:/usr/src/frontend/
      - node_modules:/usr/src/frontend/node_modules
    networks:
      - social-downloader-net
    depends_on:
      - api
      - rabbitmq
      - db

volumes:
  mongo_data:
  venv:
  node_modules:
  rabbitmq_data:
  rabbitmq_log:
  telegram_cache:

networks:
  social-downloader-net:
