
services:
  telegram:
    name: Telegram
    description: >
      Service that wraps the TDLib library to let you easily download content directly
      from your Telegram account.
    icon: telegram
    prefix: /telegram
    authentication:
      - phone_auth:
          name: Phone Number
          path: /login
          parameters:
            phone:
              name: Phone Number (with prefix)
              type: string
              required: true
          2fa: true
      - bot_token_auth:
          name: Bot Token
          path: /login
          parameters:
            bot_token:
              name: Bot Token
              type: string
              required: true
    features:
      - chats_name:
          name: Chats
          description: >
            Gets all your chats from your Telegram account.
          path: /chats-name
      - chat:
          name: Chat
          description: >
            Gets details from a chat.
          path: /chat
          parameters:
            chat_id:
              name: Chat ID
              type: string
              required: true
      - messages:
          name: Messages
          description: >
            Get messages from a chat.
          path: /messages
          parameters:
            chat_id:
              name: Chat ID
              type: int
              required: true
            limit:
              name: Number of Messages
              type: string
              required: false
      - me:
          name: Me
          description: >
            Get your account details.
          path: /me
      - search_public_chats_name:
          name: Search Public Chats
          description: >
            Searches public chats querying a keyword to be found in their username or title.
          path: /search-public-chats-name
          parameters:
            query:
              name: Query
              type: string
              required: true
      - chats:
          name: Chats
          detail: Only ID's
          description: >
            Extracted as is from the TDLib API.
            Gets all your chats ID's from your Telegram account.
          path: /chats
      - search_public_chats:
          name: Search Public Chats
          detail: Only ID's
          description: >
            Extracted as is from the TDLib API.
            Searches public chats ID's querying a keyword to be found in their username or title.
          path: /search-public-chats
          parameters:
            query:
              name: Query
              type: string
              required: true
  test-service:
    name: Reddit
    description: >
      Example service, not a real service.
    icon: reddit
    prefix: /test-service
    features:
      - chats:
          name: Test
          description: >
            Example.
          path: /test